# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: Quantifying the Commons
# All technologies used
technologies: Python
# Whether this repository should be featured on the CC Open Source site
featured: false
# Slack channel name
slack: "cc-dev-quantifying"
