name: Static Analysis

on:
  push:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:

    # https://github.com/actions/setup-python
    - name: Install Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pipenv
      run: |
        pip install --upgrade pip
        pip install pipenv

    # https://github.com/actions/checkout
    - name: Checkout quantifying
      uses: actions/checkout@v4

    - name: Install Python dependencies
      # Install _only_ [dev-packages]
      run: pipenv sync --categories dev-packages --system

    - name: pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
